plugins {
    id 'net.neoforged.moddev' version '2.0.141'
    id 'com.diffplug.spotless' version '7.2.1'
}

apply plugin: 'idea'
apply plugin: 'maven-publish'
apply plugin: 'jacoco'

// Determine build number
String build_number = "DEV" // this will be referenced as simply build_number from now on.
if (System.getenv().BUILD_NUMBER)
    build_number = System.getenv().BUILD_NUMBER
if (System.getenv().GITHUB_RUN_ID)
    build_number = System.getenv().GITHUB_RUN_NUMBER
if (System.getenv().RELEASE)
    build_number = "RELEASE"
logger.lifecycle "BUILDING VERSION: " + build_number

// Include build number in version
if (build_number.equals("RELEASE"))
    version = "${project.mod_version}"
else
    version = "${project.mod_version}-${build_number}"

base {
    archivesName = "${mod_id}-${minecraft_version}-neoforge"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version)
}
compileJava.options.compilerArgs << "-Xmaxerrs" << "9999"

// Load secrets
def getSecrets() {
    Properties props = new Properties()
    if (file('./secrets.properties').exists()) {
        props.load(new FileInputStream(file('./secrets.properties')))
    }
    return props
}
//ext {
    Properties secrets = getSecrets();
    secrets.build_number = build_number;
//}

sourceSets {
    main
    test
}
sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    modLib
    implementation.extendsFrom modLib
}

repositories {
    mavenCentral()
	mavenLocal()
    maven {
        url "https://maven.pkg.github.com/CyclopsMC/packages"
        credentials {
            username = project.findProperty("gpr.user") ?: System.getenv("MAVEN_USERNAME") ?: System.getenv("GITHUB_USER")
            password = project.findProperty("gpr.key") ?: System.getenv("MAVEN_KEY") ?: System.getenv("GITHUB_TOKEN")
        }
    }
    maven {
        name = "Refined Storage"
        url = uri("https://maven.creeperhost.net")
        content {
            includeGroup("com.refinedmods.refinedstorage")
        }
    }
//    maven {
//        url 'https://dvs1.progwml6.com/files/maven/'
//    }
    maven {
        url 'https://maven.k-4u.nl'
    }
    /*maven {
        name 'Tehnut'
        url 'https://tehnut.info/maven/'
    }*/
//    maven {
//        url "https://repo.refinedmods.com/"
//    }
    maven {
        url = "https://minecraft.curseforge.com/api/maven/"
    }
    maven {
        name 'jared'
        url 'https://maven.blamejared.com/'
    }
    maven {
        name "REI"
        url "https://maven.shedaniel.me/"
    }
    maven {
        url "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        url = 'https://maven.minecraftforge.net/'
    }
    exclusiveContent {
        forRepository {
            maven { url = "https://maven.ryanhcode.dev/releases" }
        }
        filter {
            includeGroup("dev.ryanhcode.sable-companion")
        }
    }
}

dependencies {
	// Add something like 'integrateddynamics_version_local=0.1.0-DEV' to your secrets.properties if you want to use a custom local Integrated Dynamics version.
    if(secrets.integrateddynamics_version_local) {
        implementation "org.cyclops.integrateddynamics:integrateddynamics-${project.minecraft_version}-neoforge:${secrets.integrateddynamics_version_local}:slim"
        modLib "com.google.re2j:re2j:1.1"
    } else {
        implementation("org.cyclops.integrateddynamics:integrateddynamics-${project.minecraft_version}-neoforge:${project.integrateddynamics_version}:slim") {
            exclude group: 'org.cyclops.cyclopscore', module: 'cyclopscore'
            exclude group: 'org.cyclops.commoncapabilities', module: 'commoncapabilities'
        }
        modLib "com.google.re2j:re2j:1.1"
    }
    // Add something like 'cyclopscore_version_local=0.1.0-DEV' to your secrets.properties if you want to use a custom local CyclopsCore version.
    if(secrets.cyclopscore_version_local) {
        implementation "org.cyclops.cyclopscore:cyclopscore-${project.minecraft_version}-neoforge:${secrets.cyclopscore_version_local}"
    } else {
        implementation "org.cyclops.cyclopscore:cyclopscore-${project.minecraft_version}-neoforge:${project.cyclopscore_version}"
    }

    implementation("org.cyclops.commoncapabilities:commoncapabilities-${project.minecraft_version}-neoforge:${project.commoncapabilities_version}") { // https://dl.bintray.com/cyclopsmc/dev/org/cyclops/commoncapabilities/CommonCapabilities/
        exclude group: 'org.cyclops.cyclopscore', module: 'cyclopscore'
    }

    implementation("mezz.jei:jei-${project.jei_version}") { // https://maven.blamejared.com/mezz/jei/
        transitive = false
    }
    //compileOnly "mcjty.theoneprobe:theoneprobe:${project.theoneprobe_version}" // https://maven.k-4u.nl/mcjty/theoneprobe/theoneprobe/
    // TODO: for some reason using the following in runtime breaks ForgeGradle
    /*runtimeOnly(fg.deobf("mcjty.theoneprobe:theoneprobe:${project.theoneprobe_version}")) { // https://maven.k-4u.nl
        transitive = false
    }*/

    implementation("com.refinedmods.refinedstorage:refinedstorage-neoforge:${refinedstorage_version}") { // https://github.com/refinedmods/refinedstorage2/releases
        transitive = false
    }

    implementation("com.github.glitchfiend:TerraBlender-neoforge:${project.terrablender_version}") // MCF: https://www.curseforge.com/minecraft/mc-mods/terrablender/files/all?page=1&pageSize=20

    compileOnly("me.shedaniel:RoughlyEnoughItems-neoforge:${rei_version}") // https://maven.shedaniel.me/me/shedaniel/RoughlyEnoughItems-neoforge/
    implementation("me.shedaniel.cloth:cloth-config-neoforge:$cloth_config_version"); // https://maven.shedaniel.me/me/shedaniel/cloth/cloth-config-neoforge/
    implementation("dev.architectury:architectury-neoforge:$architectury_version"); // https://maven.shedaniel.me/dev/architectury/architectury-neoforge/

    implementation("curse.maven:jade-324717:${jade_version}") // https://www.curseforge.com/minecraft/mc-mods/jade

//    implementation("curse.maven:create-aeronautics-676721:${create_aeronautics_version}")
//    implementation("curse.maven:sable-1312371:${sable_version}")
//    implementation("curse.maven:create-328085:${create_version}")
//    compileOnly("dev.ryanhcode.sable-companion:sable-companion-common-${project.sable_companion_version}")

}

neoForge {
    version = "${neoforge_version}"

    // Automatically enable neoforge AccessTransformers if the file exists
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers = [ at.absolutePath ]
    }

    validateAccessTransformers = true

    runs {
        client {
            client()
        }
        server {
            server()
        }
        gameTestServer {
            type = "gameTestServer"
        }
        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
            systemProperty 'neoforge.enabledGameTestNamespaces', "cyclopscore,${mod_id}"
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

jar {
    manifest {
        attributes([
                "FMLAT": "accesstransformer.cfg",
                "Specification-Title": "${project.name}",
                "Specification-Vendor": "rubensworks",
                "Specification-Version": "${project.mod_version}",
                "Implementation-Title": "${project.name}",
                "Implementation-Version": "${project.mod_version}",
                "Implementation-Vendor" :"rubensworks",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

task sourcesJar(type: Jar) {
    duplicatesStrategy(DuplicatesStrategy.FAIL)
    archiveClassifier.set('sources')
    from sourceSets.main.allJava
}

task javadocJar(type: Jar, dependsOn: javadoc) {
    duplicatesStrategy(DuplicatesStrategy.FAIL)
    archiveClassifier.set('javadoc')
    from javadoc.destinationDir
}

artifacts {
    archives sourcesJar
    archives javadocJar
}

// Replace properties in files
processResources {
    def expandProps = [
            'mod_version'                           : project.version,
            'group'                                 : project.group, //Else we target the task's group.
            'minecraft_version'                     : minecraft_version,
            'mod_name'                              : mod_name,
            'mod_author'                            : mod_author,
            'mod_id'                                : mod_id,
            'license'                               : license,
            'issue_tracker_url'                     : issue_tracker_url,
            'display_url'                           : display_url,
            'description'                           : project.description,
            'neoforge_version'                      : neoforge_version,
            'neoforge_loader_version_range'         : neoforge_loader_version_range,
            'java_version'                          : java_version,
            'cyclopscore_version'                   : cyclopscore_version,
            'cyclopscore_version_semver'            : cyclopscore_version.replaceAll("-.*\$", ""),
            'integrateddynamics_version'            : integrateddynamics_version,
            'integrateddynamics_version_semver'     : integrateddynamics_version.replaceAll("-.*\$", "")
    ]

    filesMatching(['pack.mcmeta', 'META-INF/mods.toml', 'META-INF/neoforge.mods.toml', 'mixins.*.json']) {
        expand expandProps
    }
    inputs.properties(expandProps)
}

publishing {
    repositories {
        if (project.hasProperty("filesmaven_url")) {
            logger.info('Publishing to files server')
            maven {
                url project.filesmaven_url
                credentials {
                    username = project.filesmaven_username
                    password = project.filesmaven_key
                }
            }
        } else if (System.getenv("MAVEN_URL")) {
            logger.info('Publishing to files server')
            maven {
                url System.getenv("MAVEN_URL")
                credentials {
                    username = System.getenv("MAVEN_USERNAME")
                    password = System.getenv("MAVEN_KEY")
                }
            }
        } else {
            logger.error('No maven repo was set!')
        }
    }

    publications { PublicationContainer publicationContainer ->
        publicationContainer.register("maven", MavenPublication) { MavenPublication publication ->
            publication.artifacts = [jar, javadocJar, sourcesJar]
            publication.artifactId = project.base.archivesName.get().toLowerCase() // GH can't handle uppercase...
        }
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
        for (String excludeDirName in ["run", "out", "logs", "gradle"]) {
            File excludeDir = new File(projectDir, excludeDirName)
            excludeDirs.add(excludeDir)
        }
    }
}

jacocoTestReport {
    // Include unit and game test coverage
    executionData fileTree(project.buildDir).include("jacoco/*.exec")
    reports {
        xml.required = true
        html.required = true
    }
}

// Also measure coverage for game tests
jacocoTestReport.dependsOn test, runGameTestServer
jacoco {
    toolVersion = "0.8.14"
    applyTo runGameTestServer
}

sourceSets {
    main {
        java {
            // TODO: temporarily disable some mod compats
            exclude '**/modcompat/almostunified/**'
            exclude '**/modcompat/charset/**'
            exclude '**/modcompat/forestry/**'
            exclude '**/modcompat/ic2/**'
            exclude '**/modcompat/immersiveengineering/**'
            exclude '**/modcompat/mcmultipart/**'
            exclude '**/modcompat/signals/**'
            exclude '**/modcompat/tconstruct/**'
            exclude '**/modcompat/thaumcraft/**'
            exclude '**/modcompat/top/**'
            exclude '**/modcompat/createaeronautics/**'
        }
    }
}

spotless {
    java {
        target project.fileTree(project.rootDir) {
            include '**/java/org/cyclops/**/*.java'
            // TODO: temporarily disable some mod compats
            exclude '**/modcompat/almostunified/**'
            exclude '**/modcompat/charset/**'
            exclude '**/modcompat/forestry/**'
            exclude '**/modcompat/ic2/**'
            exclude '**/modcompat/immersiveengineering/**'
            exclude '**/modcompat/mcmultipart/**'
            exclude '**/modcompat/signals/**'
            exclude '**/modcompat/tconstruct/**'
            exclude '**/modcompat/thaumcraft/**'
            exclude '**/modcompat/top/**'
            exclude '**/modcompat/createaeronautics/**'
        }

        endWithNewline()
        trimTrailingWhitespace()
        removeUnusedImports()
        leadingTabsToSpaces()
    }
}
spotlessJava.mustRunAfter(javadoc)
spotlessJava.mustRunAfter(compileTestJava)
spotlessJava.mustRunAfter(test)

tasks.register('updateGitHooks', Copy) {
    from './scripts/pre-commit'
    into './.git/hooks'
}
compileJava.dependsOn updateGitHooks
